apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plumber.fullname" . }}
  labels:
    {{- include "plumber.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "plumber.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "plumber.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plumber.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/plumber-linux", "relay", "kafka"]
          ports:
            - containerPort: 9191
          env:
            - name: PLUMBER_RELAY_TOKEN
              value: {{ .Values.plumber_relay_token }}
            - name: PLUMBER_RELAY_KAFKA_ADDRESS
              value: {{ .Values.plumber_relay_kafka_address }}
            - name: PLUMBER_RELAY_KAFKA_TOPIC
              value: {{ .Values.plumber_relay_kafka_topic }}
            - name: PLUMBER_RELAY_KAFKA_GROUP_ID
              value: {{ .Values.plumber_relay_kafka_group_id }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
